spring.profiles.active: dev

spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  server:
    ssl:
      key-store: src/main/resources/bugReport.jks
      key-store-password: sE0/c+PG8GvBvUx+h3LGae/+E3MptoILayZ4oXV4K1NRYAXNXAxNpWZBAsRlavfQ

      key-store-type: JKS
  workingDir: src/main/resources/tmp/bugReport
  roles: ADMIN,USER,EMPLOYEE,MANAGER
  crypto:
    key: claytonsKey

  mySqlDatasource:
    url: jdbc:mysql://localhost:3306/cecs544
    username: root
    password: UFNF7h9EhwcHo4o6q1l7NtFGIBWtlG9lcXzVskdlaKE=
    driver: com.mysql.cj.jdbc.Driver
  cache:
    clearSchedule: 0 0 * * * *
  aws:
    regionName: us-west-1
    s3:
      localUri: http://localhost:9000
      bucketName: cecs-544-bug-bucket
      accessKey: nBx7JWgR1+KLmlblB2WgtIuwBmrxA5Z9iCxHrJqLHIdj4eqN4boI62M3EXcf8E8s
      secretKey: bg+iRVHp751fGS/bSn8dRDX1j6F7GcGy6Mj2Vt/RgXlUjJYo/4WxIewRL0gsPEi1b6VjA/aO5gdFrU3famcacw==